-- Users table seeds here (Example)
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (1,true,'HTML','What is HTML?', 'science', 'https://www.udacity.com/blog/wp-content/uploads/2020/06/HTML_Blog-scaled.jpeg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (2,true,'CSS','What is CSS?', 'science', 'https://www.thatcompany.com/wp-content/uploads/2019/03/css-graphic-1.png');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (3,true,'JavaScript','What is JavaScript?', 'science', 'https://geekboots.sfo2.cdn.digitaloceanspaces.com/post/javascript-1567486564472.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (4, true, 'Geography', 'Test your Geography!', 'geography', 'https://media.istockphoto.com/vectors/geography-open-book-with-hand-drawn-word-geography-and-doodle-vector-id1257796192?s=612x612');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (5, true, 'Pop Culture!', 'Do you know your pop?', 'pop-culture', 'http://www.theinclusionsolution.me/wp-content/uploads/2014/10/Pop-Culture-620x330.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (6, true, 'Biology', 'Do you know your science?', 'science', 'https://thumbs.dreamstime.com/b/biology-biology-doodles-lettering-vector-illustration-biology-biology-doodles-lettering-135179613.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (7, true, 'Chemesty', 'Do you Chem?', 'science', 'https://www.wyzant.com/blog/wp-content/uploads/2020/09/Most-Difficult-Aspects-of-Chemistry-and-How-to-Overcome-Them.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (8, true, 'Movies', 'Do you know the silver screen?', 'pop-culture', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/fall-movies-index-1628968089.jpg?crop=0.470xw:1.00xh;0.353xw,0&resize=640:*');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (9,
true, 'TV Shows', 'Do you know the small screen?', 'pop-culture', 'https://scriptmag.com/.image/t_share/MTY3Mzc5MDYyMDQ3NjQ3MzQ0/image-placeholder-title.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (10, true, 'Cartoons', 'Do you know your cartoons?', 'pop-culture', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cartoons-year-born-1525733963.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (11, true, 'The Simpsons', 'Do you know The Simpsons?', 'pop-culture', 'http://i.imgur.com/Tnv3qdD.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (12, true, 'Rivers', 'Do you know your rivers?', 'geography', 'https://earthsky.org/upl/2021/03/river-aerial-shot-e1615896010133.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (13, true, 'Mountains', 'Do you know your mountains?', 'geography', 'https://www.atlasandboots.com/wp-content/uploads/2019/05/ama-dablam2-most-beautiful-mountains-in-the-world.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (14, true, 'Countries of the World', 'Do you know your countries?', 'geography', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOP0ajUSYAv2WocFRty4yp6-Zaqyio7pWxRQ&usqp=CAU');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (15, true, 'Captial Cities', 'Do you know your capital cities?', 'geography', 'https://images-na.ssl-images-amazon.com/images/I/81Q1GHQs1KL.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (1, true, 'Sports', 'Do you know your sports?', 'sports', 'https://media.npr.org/assets/img/2020/06/10/gettyimages-200199027-001-b5fb3d8d8469ab744d9e97706fa67bc5c0e4fa40.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (2, true, 'Basketball', 'Do you know your basketball?', 'sports', 'https://sportshub.cbsistatic.com/i/r/2020/01/28/3454846d-4979-470c-8a22-d7755ab12d4d/thumbnail/1200x675/137f74c409db16eec3e22b06c2be41f3/general-basketball.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (3, true, 'Soccer', 'Do you know your Soccer?', 'sports', 'https://canadasoccer.com/wp-content/uploads/2021/09/20210907_Davies.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (1, true, 'Football', 'Do you know your Football?', 'sports', 'https://media.wired.com/photos/5a3af5179b5b7950644810b9/master/w_2560%2Cc_limit/football-TA.jpg');
INSERT INTO quizzes (user_id, quiz_type, name, description, category, image_url) VALUES (2, true, 'Tennis', 'Do you know your Tennis?', 'sports', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Roger_Federer_2012_Indian_Wells.jpg/1024px-Roger_Federer_2012_Indian_Wells.jpg');
